/**
 * VISTHAAPAN Phase 6 Unsafe-Zone Engine (6C)
 * Deterministic spatial derivation of statutory Red Zones and hazard exclusion envelopes.
 * Utilizes PostGIS metric geography buffering (ST_Buffer) and geometric union (ST_UnaryUnion / ST_Union).
 *
 * NON-CONFUSION RULE:
 * Red zones are derived strictly from physical polygonal hazard footprints and metric setback buffers.
 * Never generated from district-level AI tabular risk scores.
 */

import { PoolClient } from 'pg';
import { pool, getClient } from '../db/pool.js';
import { logger } from '../utils/logger.js';
import { getOrCreateDataSource, getOrCreateDataset, getOrCreateDatasetVersion } from '../pipeline/provenance.js';
import type { GeoJsonFeatureCollection, GeoJsonFeature } from '../types/gis.js';

export interface RedZoneDerivationSummary {
  redZonesDerived: number;
  junctionsCreated: number;
  durationMs: number;
}

/**
 * Derives and populates statutory Red Zones from active hazard layers and metric buffers.
 * Maintains full referential integrity and records associative red_zone_hazards links.
 */
export async function deriveRedZonesFromHazards(): Promise<RedZoneDerivationSummary> {
  const startTime = Date.now();
  logger.info('Starting deterministic Unsafe-Zone derivation engine...');

  const client: PoolClient = await getClient();

  try {
    await client.query('BEGIN;');

    // 1. Provenance Ledger
    const sourceId = await getOrCreateDataSource(client, {
      datasetName: 'VISTHAAPAN Statutory Unsafe-Zone Engine (SIMULATED/DERIVED)',
      sourceOrganization: 'VISTHAAPAN Spatial Analytics Core',
      sourceType: 'DERIVED',
      sourceUrl: 'urn:visthaapan:gis:red-zones:v1',
      coverage: 'Chamoli Planning Area',
      confidence: 0.95,
      description: 'Statutory uninhabitable red zones derived through PostGIS spatial buffering and multi-hazard union geometry operations.',
    });

    const datasetId = await getOrCreateDataset(client, {
      sourceId,
      name: 'Derived Statutory Red Zones',
      description: 'Physical MultiPolygon exclusion zones where permanent habitation and relocation sites are strictly prohibited.',
      dataType: 'SPATIAL_VECTOR_MULTIPOLYGONS',
      format: 'POSTGIS_MULTIPOLYGON',
      coverage: 'Chamoli Planning Area',
    });

    const { id: datasetVersionId } = await getOrCreateDatasetVersion(client, {
      datasetId,
      versionNumber: 'v2026.09-RED-ZONES-V1',
      recordCount: 3,
      qualityScore: 0.97,
      processingNotes: 'Derived using metric geography buffers (ST_Buffer) and MultiPolygon normalization (ST_Multi).',
    });

    // Clean up existing red zones for idempotency
    await client.query('DELETE FROM red_zone_hazards;');
    await client.query('DELETE FROM red_zones;');

    // 2. Query active hazard layers
    const { rows: hazardRows } = await client.query<{
      id: string;
      name: string;
      hazard_type: string;
      severity: string;
      confidence: string;
      buffer_radius_meters: string;
      exclusion_type: string;
    }>(`
      SELECT 
        id,
        name,
        hazard_type,
        severity,
        confidence,
        buffer_radius_meters,
        CASE 
          WHEN hazard_type = 'subsidence' THEN 'HARD_HAZARD'
          WHEN hazard_type = 'flash_flood' THEN 'BUFFER_SETBACK'
          ELSE 'SLOPE_INSTABILITY'
        END AS exclusion_type
      FROM hazard_layers
      ORDER BY severity DESC;
    `);

    if (hazardRows.length === 0) {
      logger.warn('No hazard layers found. Skipping red zone derivation.');
      await client.query('COMMIT;');
      return { redZonesDerived: 0, junctionsCreated: 0, durationMs: Date.now() - startTime };
    }

    let redZonesCount = 0;
    let junctionsCount = 0;

    // 3. Derive a distinct Red Zone for each critical/high hazard envelope with its metric buffer
    for (const h of hazardRows) {
      const bufferMeters = parseFloat(h.buffer_radius_meters) || 0;
      const confidence = parseFloat(h.confidence) || 0.9;

      const zoneName = `${h.name.replace(' (SIMULATED)', '')} Exclusion Envelope (SIMULATED)`;
      const reason = `Model-derived exclusion zone generated by ${h.hazard_type} (${h.severity} severity) with a ${bufferMeters}m safety buffer envelope based on DM Act 2005 Sec 30(2)(v) planning criteria. Permanent habitation prohibited (SIMULATED BENCHMARK).`;

      // Apply metric buffer using geography casting and ensure valid MultiPolygon output
      const insertRes = await client.query<{ id: string }>(`
        INSERT INTO red_zones (
          name, reason, risk_threshold, confidence, exclusion_type,
          dataset_version_id, geometry, metadata
        )
        SELECT 
          $1, $2, 0.85, $3, $4, $5,
          ST_Multi(ST_Buffer(geometry::geography, $6)::geometry),
          jsonb_build_object(
            'derivedFromHazardLayerId', $7::text,
            'hazardType', $8::text,
            'bufferMeters', $6::numeric,
            'statutoryPlanningBasis', 'Disaster Management Act 2005 Sec 30(2)(v) Model Planning Criteria (SIMULATED)',
            'isGazettedOrder', false,
            'datasetClassification', 'DERIVED_BENCHMARK_MODEL'
          )
        FROM hazard_layers
        WHERE id = $7::uuid
        RETURNING id;
      `, [
        zoneName,
        reason,
        confidence,
        h.exclusion_type,
        datasetVersionId,
        bufferMeters,
        h.id,
        h.hazard_type,
      ]);

      const redZoneId = insertRes.rows[0].id;
      redZonesCount++;

      // Link to associative red_zone_hazards junction
      await client.query(`
        INSERT INTO red_zone_hazards (red_zone_id, hazard_layer_id)
        VALUES ($1, $2)
        ON CONFLICT DO NOTHING;
      `, [redZoneId, h.id]);
      junctionsCount++;
    }

    // 4. Also derive a Unified Consolidated Red Zone representing all combined hazards
    const unifiedName = 'Consolidated Multi-Hazard Exclusion Zone (Chamoli Composite) (SIMULATED)';
    const unifiedReason = 'Algorithmic geometric union (PostGIS ST_UnaryUnion) of all active simulated subsidence, flash flood, and landslide hazard buffers in Chamoli planning sector according to DM Act 2005 planning guidelines.';

    const unionRes = await client.query<{ id: string }>(`
      INSERT INTO red_zones (
        name, reason, risk_threshold, confidence, exclusion_type,
        dataset_version_id, geometry, metadata
      )
      SELECT 
        $1, $2, 0.90, 0.95, 'HARD_HAZARD', $3,
        ST_Multi(ST_UnaryUnion(ST_Collect(geometry))),
        jsonb_build_object(
          'composite', true,
          'totalLayersCombined', count(*),
          'methodology', 'PostGIS ST_UnaryUnion over buffered hazard footprints',
          'isGazettedOrder', false,
          'datasetClassification', 'DERIVED_BENCHMARK_MODEL'
        )
      FROM red_zones
      RETURNING id;
    `, [unifiedName, unifiedReason, datasetVersionId]);

    const compositeRedZoneId = unionRes.rows[0].id;
    redZonesCount++;

    // Link composite zone to all underlying hazard layers
    for (const h of hazardRows) {
      await client.query(`
        INSERT INTO red_zone_hazards (red_zone_id, hazard_layer_id)
        VALUES ($1, $2)
        ON CONFLICT DO NOTHING;
      `, [compositeRedZoneId, h.id]);
      junctionsCount++;
    }

    await client.query('COMMIT;');
    const durationMs = Date.now() - startTime;

    logger.info(
      { redZonesCount, junctionsCount, durationMs },
      'Statutory Red Zones successfully derived and linked to hazard layers.'
    );

    return {
      redZonesDerived: redZonesCount,
      junctionsCreated: junctionsCount,
      durationMs,
    };
  } catch (err: any) {
    await client.query('ROLLBACK;');
    logger.error({ err }, 'Red zone derivation failed.');
    throw err;
  } finally {
    client.release();
  }
}

/**
 * Retrieves all statutory Red Zones as an RFC 7946 GeoJSON FeatureCollection.
 */
export async function getRedZonesGeoJson(): Promise<GeoJsonFeatureCollection> {
  const query = `
    SELECT 
      rz.id,
      rz.name,
      rz.reason,
      rz.risk_threshold,
      rz.confidence,
      rz.exclusion_type,
      rz.metadata,
      ST_AsGeoJSON(rz.geometry)::json as geojson_geom,
      COALESCE(
        json_agg(
          json_build_object(
            'hazardLayerId', hl.id,
            'name', hl.name,
            'hazardType', hl.hazard_type,
            'severity', hl.severity
          )
        ) FILTER (WHERE hl.id IS NOT NULL),
        '[]'::json
      ) as linked_hazards
    FROM red_zones rz
    LEFT JOIN red_zone_hazards rzh ON rzh.red_zone_id = rz.id
    LEFT JOIN hazard_layers hl ON hl.id = rzh.hazard_layer_id
    GROUP BY rz.id
    ORDER BY rz.created_at ASC;
  `;

  const { rows } = await pool.query(query);

  const features: GeoJsonFeature[] = rows.map((r) => ({
    type: 'Feature',
    id: r.id,
    geometry: r.geojson_geom,
    properties: {
      name: r.name,
      reason: r.reason,
      riskThreshold: r.risk_threshold ? parseFloat(r.risk_threshold) : 0.85,
      confidence: r.confidence ? parseFloat(r.confidence) : 0.95,
      exclusionType: r.exclusion_type,
      metadata: r.metadata || {},
      linkedHazards: r.linked_hazards,
    },
  }));

  return {
    type: 'FeatureCollection',
    features,
    metadata: {
      count: features.length,
      source: 'PostGIS red_zones (DERIVED_BENCHMARK_MODEL)',
      datasetClassification: 'DERIVED_BENCHMARK_ENVELOPES',
      statutoryAuthorityBasis: 'Disaster Management Act 2005 Sec 30(2)(v) Model Planning Criteria (SIMULATED BENCHMARK)',
      statutoryDisclaimer: 'Exclusion zones are algorithmically derived spatial models for disaster mitigation planning; NOT legally gazetted executive orders.',
    },
  };
}

/**
 * Checks if a geographic point (lat, lon) intersects any Red Zone.
 */
export async function checkPointInsideRedZone(
  lat: number,
  lon: number
): Promise<{ isInside: boolean; redZoneNames: string[] }> {
  const query = `
    SELECT rz.name
    FROM red_zones rz
    WHERE ST_Intersects(
      rz.geometry,
      ST_SetSRID(ST_MakePoint($1, $2), 4326)
    );
  `;
  const { rows } = await pool.query<{ name: string }>(query, [lon, lat]);
  return {
    isInside: rows.length > 0,
    redZoneNames: rows.map((r) => r.name),
  };
}

// CLI execution entrypoint
const isMain = process.argv[1] === import.meta.filename;
if (isMain) {
  deriveRedZonesFromHazards()
    .then((res) => {
      console.log('✓ Unsafe zones derived successfully:', res);
      return pool.end();
    })
    .catch((err) => {
      console.error('Fatal red zone derivation error:', err);
      pool.end().finally(() => process.exit(1));
    });
}
